# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/tenable/terrascan
    rev: v1.18.0
    hooks:
    - id: terraform-pre-commit      
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: "2.2.278" # change to tag or sha
    hooks:
      - id: checkov
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
